HI,
THIS IS A SIMPLE FILE TO LEARN THE WORKING OF DIFFMERGE TOOL,
AND MY GOAL IS TO STUDY  RELATION BETWEEN BASE,LOCAL AND 
REMOTE REPOS WHICH ARISE WHEN CONFLICTS OCCURS USING THE DIFFMERGE TOOL.


This is after resolving merge conflicts
